name: Process videos

on:
  workflow_dispatch:
  push:
    paths:
      - 'tasks/**.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      - run: sudo apt install -y nscd
      - run: yarn install
      - run: yarn process
        env:
          NEXT_PUBLIC_LIVEPEER_API_KEY: ${{ secrets.NEXT_PUBLIC_LIVEPEER_API_KEY }}
          DEPLOYER_KEY: ${{ secrets.DEPLOYER_KEY }}
          VERCEL_DEPLOY_KEY: ${{ secrets.VERCEL_DEPLOY_KEY }}
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: '[ignore] Process video'
