name: Process videos

on:
  workflow_dispatch:
  push:
    paths:
      - 'tasks/**.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn install

      - name: Process videos
        run: yarn process

      - name: Commit updates
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: '[ignore] Process video'
